// Generated from the Footdrums forScore setlist: each score in
// "Footdrums (Test).4ss" has a MIDI Open command of Program Change <program>
// on channel 1 (forScore stores it as raw hex, e.g. "C0 32" = program 50).
export const FOOTDRUMS_SONGS: { title: string; program: number }[] = [
  { title: "Wish You Well", program: 0 },
  { title: "I'm Gonna Be (500 Miles)", program: 1 },
  { title: "How You Remind Me", program: 2 },
  { title: "What About Me?", program: 3 },
  { title: "Perfect", program: 4 },
  { title: "Yesterday", program: 5 },
  { title: "Love Story", program: 6 },
  { title: "Rolling in the Deep", program: 7 },
  { title: "Don't Stop", program: 8 },
  { title: "Brown Eyed Girl", program: 9 },
  { title: "Watermelon Sugar", program: 10 },
  { title: "Riptide", program: 11 },
  { title: "Someone You Loved", program: 12 },
  { title: "Stay", program: 13 },
  { title: "Shape Of You", program: 14 },
  { title: "Levitating", program: 15 },
  { title: "Blinding Lights", program: 16 },
  { title: "Scar", program: 17 },
  { title: "Isn't She Lovely", program: 18 },
  { title: "Go Your Own Way", program: 19 },
  { title: "Murder on the Dancefloor", program: 20 },
  { title: "Espresso", program: 21 },
  { title: "Good Luck Babe", program: 22 },
  { title: "Don't Look Back In Anger", program: 23 },
  { title: "Unwritten", program: 24 },
  { title: "Iris", program: 25 },
  { title: "Valerie", program: 26 },
  { title: "Take Me Home, Country Roads", program: 27 },
  { title: "Thinking Out Loud", program: 28 },
  { title: "Upside Down", program: 29 },
  { title: "Summer of 69", program: 30 },
  { title: "Never Tear Us Apart", program: 31 },
  { title: "I've Just Seen A Face", program: 32 },
  { title: "In The Summertime", program: 33 },
  { title: "I Need A Dollar", program: 34 },
  { title: "High And Dry", program: 35 },
  { title: "Boys Don't Cry", program: 36 },
  { title: "Better Together", program: 37 },
  { title: "Banana Pancakes", program: 38 },
  { title: "Sex on Fire", program: 39 },
  { title: "Teenage Dirtbag", program: 40 },
  { title: "Yellow", program: 41 },
  { title: "Angels", program: 42 },
  { title: "Beautiful Crazy", program: 43 },
  { title: "Have You Ever Seen The Rain", program: 44 },
  { title: "My Happiness", program: 45 },
  { title: "Stick Season", program: 46 },
  { title: "Linger", program: 47 },
  { title: "Electric Feel", program: 48 },
  { title: "Flame Trees", program: 49 },
  { title: "Get Lucky", program: 50 },
  { title: "All of Me", program: 51 },
  { title: "Chandelier", program: 52 },
  { title: "Better Be Home Soon", program: 53 },
  { title: "She's Electric", program: 54 },
  { title: "April Sun In Cuba", program: 55 },
  { title: "Bodyguard", program: 56 },
  { title: "Someday", program: 57 },
  { title: "Lost", program: 58 },
  { title: "Satisfaction", program: 59 },
  { title: "Mr. Brightside", program: 60 },
  { title: "Free Fallin'", program: 61 },
  { title: "Don't Stop Believin'", program: 62 },
  { title: "Jolene", program: 63 },
  { title: "Seven Nation Army", program: 64 },
  { title: "Shut Up and Dance", program: 65 },
  { title: "Sittin’ On The Dock of the Bay", program: 66 },
  { title: "Wagon Wheel", program: 67 },
  { title: "Zombie", program: 68 },
  { title: "Wonderwall", program: 69 },
  { title: "Uptown Girl", program: 70 },
  { title: "Dreams", program: 71 },
  { title: "Come Together", program: 72 },
  { title: "The Best", program: 73 },
  { title: "Hey Jude", program: 74 },
  { title: "Sk8er Boi", program: 75 },
  { title: "All Day and All of the Night", program: 76 },
  { title: "Can't Buy Me Love", program: 77 },
  { title: "Castle on the Hill", program: 78 },
  { title: "Build Me Up Buttercup", program: 79 },
  { title: "Sweet Caroline", program: 80 },
  { title: "I'm A Believer", program: 81 },
  { title: "I Love Rock n Roll", program: 82 },
  { title: "Don't Stop Me Now", program: 83 },
  { title: "Crazy Little Thing Called Love", program: 84 },
  { title: "Dancing Queen", program: 85 },
  { title: "Man! I Feel Like A Woman!", program: 86 },
  { title: "Pink Pony Club", program: 87 },
  { title: "The Gambler", program: 88 },
  { title: "Baby Ive Got You On My Mind", program: 89 },
  { title: "Don’t Dream Its Over", program: 90 },
  { title: "Roxanne", program: 91 },
  { title: "Somebody That I Used To Know", program: 92 },
  { title: "Good Riddance (Time Of Your Life)", program: 93 },
  { title: "Vienna", program: 94 },
  { title: "Super Rich Kids", program: 95 },
  { title: "Creep", program: 96 },
  { title: "Dirty Work", program: 97 },
  { title: "Highway To Hell", program: 98 },
  { title: "I Want To Break Free", program: 99 },
  { title: "Tomorrow", program: 100 },
  { title: "All The Small Things", program: 101 },
  { title: "Happy Birthday", program: 102 },
  { title: "Dracula", program: 103 },
  { title: "Man I Need", program: 104 },
  { title: "Nice To Each Other", program: 105 },
  { title: "Feel Good Inc.", program: 106 },
  { title: "Song 2", program: 107 },
  { title: "Am I Ever Gonna See Your Face Again", program: 108 },
  { title: "Billie Jean", program: 109 },
  { title: "This Love", program: 110 },
  { title: "Viva La Vida", program: 111 },
  { title: "12 To 12", program: 112 },
  { title: "Where The Wild Things Are", program: 113 },
  { title: "9 To 5", program: 114 },
  { title: "Rocket Man", program: 115 },
  { title: "Cruel Summer", program: 116 },
  { title: "Human", program: 117 },
  { title: "No One Noticed", program: 118 },
  { title: "Bennie and the Jets", program: 119 },
  { title: "Your Song", program: 120 },
];
